SchemaVersion: '1.0'
SageMaker:
  PythonSDK:
    Modules:
      RemoteFunction:
        Dependencies: ./requirements.txt
        ImageUri: '763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.4-gpu-py311'
        InstanceType: ml.g5.12xlarge
        IncludeLocalWorkDir: true
        PreExecutionCommands:
          - 'export NCCL_P2P_DISABLE=1'
        CustomFileFilter:
          IgnoreNamePatterns:
          - "data/*"
          - "models/*"
          - "*.ipynb"
          - "*.csv"
          - "*.md"
          - "__pycache__"
          - ".git*" #do not serialize anything git related
          - ".github/" #do not serialize github folder
          - ".venv" #do not serialize local virtual environment
        #RoleArn: RoleArn required if you are running the notebooks from a local IDE
  Model:
    EnableNetworkIsolation: false
